### ISSUE TITLE
Let Users Filter Samples With Numerical Ranges Instead of Single Values For Numerical Categories

### ISSUE THREAD

**Issue by Alevarias** [wejlab/curatedTBExplorer#16]
As it stands, for the numerical categories, the filter page only lets you filter for a single number. Adding the ability to choose a range would greatly expand the use and applications of this function. 

One example would be letting the user filter for samples of age 1 to 12 instead of just all samples of age 12.

**Comment by Alevarias** [comment]
Please added this feature to the age filter. It's unclear if there are other numerical values that also need a range selection, but age seems to be the main one we needed. I'm closing this for now, but if there are any other ranges we need to add, we can reopen this issue.

**Comment by pleaselukau** [comment]
I am still working on removing completely that filter for studies that don't have age data, or it shows "Nan-Nan"

**Comment by Alevarias** [comment]
Whoops, I'll re-open it then

**Comment by pleaselukau** [comment]
Works great now, filter is disabled for column that do not contain the data(No NA option anymore). I am closing this.
